/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package glyka.timeclock.app;

import glyka.timeclock.list.LinkedList;

import static glyka.timeclock.utilities.StringUtils.join;
import static glyka.timeclock.utilities.StringUtils.split;
import static glyka.timeclock.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
