/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package glyka.timeclock;

import javax.swing.*;

public class App {
    public static void main(String[] argv) throws Exception {
        // set look and feel to the system look and feel
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GlykaGUI().setVisible(true);
            }
        });
    }
}
